// <auto-generated />
using System;
using AgendaApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaApi.Infrastructure.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    [Migration("20260825202553_TurnFailures")]
    partial class TurnFailures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaApi.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("IdAppointment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_appointment");

                    b.Property<DateTime?>("ConfirmadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("confirmado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("estado");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("external_event_id");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inicio");

                    b.Property<Guid>("IdClient")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_client");

                    b.Property<Guid?>("IdProfessional")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_professional");

                    b.Property<Guid>("IdServiceType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_service_type");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notas");

                    b.Property<DateTime?>("RecordatorioEnviadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("recordatorio_enviado_en");

                    b.HasKey("IdAppointment");

                    b.HasIndex("Estado");

                    b.HasIndex("ExternalEventId");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdProfessional");

                    b.HasIndex("IdServiceType");

                    b.HasIndex("IdTenant", "FechaInicio");

                    b.HasIndex("IdTenant", "IdProfessional", "FechaInicio");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.AvailabilityException", b =>
                {
                    b.Property<Guid>("IdAvailabilityException")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_availability_exception");

                    b.Property<bool>("DiaCompleto")
                        .HasColumnType("bit")
                        .HasColumnName("dia_completo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<Guid?>("IdProfessional")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_professional");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("motivo");

                    b.HasKey("IdAvailabilityException");

                    b.HasIndex("IdTenant", "Fecha", "IdProfessional");

                    b.ToTable("availability_exceptions", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.AvailabilityRule", b =>
                {
                    b.Property<Guid>("IdAvailabilityRule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_availability_rule");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int")
                        .HasColumnName("dia_semana");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<Guid?>("IdProfessional")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_professional");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.HasKey("IdAvailabilityRule");

                    b.HasIndex("IdTenant", "IdProfessional");

                    b.ToTable("availability_rules", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.CalendarConnection", b =>
                {
                    b.Property<Guid>("IdCalendarConnection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_calendar_connection");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("access_token_encrypted");

                    b.Property<string>("AccountEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("account_email");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CalendarId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("calendar_id");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.Property<string>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refresh_token_encrypted");

                    b.Property<DateTime?>("SyncChannelExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sync_channel_expires_at");

                    b.Property<string>("SyncChannelId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("sync_channel_id");

                    b.Property<string>("SyncResourceId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sync_resource_id");

                    b.Property<string>("SyncToken")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("sync_token");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("token_expires_at");

                    b.HasKey("IdCalendarConnection");

                    b.HasIndex("IdTenant")
                        .IsUnique();

                    b.ToTable("calendar_connections", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_client");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("nuevo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notas");

                    b.Property<DateTime?>("ProximaCita")
                        .HasColumnType("datetime2")
                        .HasColumnName("proxima_cita");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UltimaInteraccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultima_interaccion");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("username");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("whatsapp");

                    b.HasKey("IdClient");

                    b.HasIndex("IdTenant", "UserId")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.HasIndex("IdTenant", "WhatsApp")
                        .IsUnique()
                        .HasFilter("[whatsapp] <> ''");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("IdConversationMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_conversation_message");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.Property<string>("PhoneCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("phone_cliente");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.HasKey("IdConversationMessage");

                    b.HasIndex("IdTenant", "PhoneCliente", "FechaCreacion");

                    b.ToTable("conversation_messages", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.Professional", b =>
                {
                    b.Property<Guid>("IdProfessional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_professional");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProfessional");

                    b.HasIndex("IdTenant", "Nombre");

                    b.ToTable("professionals", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.ProfessionalService", b =>
                {
                    b.Property<Guid>("IdProfessional")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_professional");

                    b.Property<Guid>("IdServiceType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_service_type");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.HasKey("IdProfessional", "IdServiceType");

                    b.HasIndex("IdServiceType");

                    b.ToTable("professional_services", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.ReminderLog", b =>
                {
                    b.Property<Guid>("IdReminderLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_reminder_log");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("error");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("sent")
                        .HasColumnName("estado");

                    b.Property<int>("Etapa")
                        .HasColumnType("int")
                        .HasColumnName("etapa");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaIntento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_intento");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_programada");

                    b.Property<Guid>("IdAppointment")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_appointment");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.Property<int>("Reintentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("reintentos");

                    b.Property<string>("WamId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("wamid");

                    b.HasKey("IdReminderLog");

                    b.HasIndex("IdTenant");

                    b.HasIndex("WamId");

                    b.HasIndex("IdAppointment", "Etapa");

                    b.ToTable("reminder_logs", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.ServiceType", b =>
                {
                    b.Property<Guid>("IdServiceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_service_type");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("BufferMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("buffer_minutos");

                    b.Property<int>("CapacidadMaxima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("capacidad_maxima");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int")
                        .HasColumnName("duracion_minutos");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdServiceType");

                    b.HasIndex("IdTenant");

                    b.ToTable("service_types", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("IdTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("AntelacionMaximaDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("antelacion_maxima_dias");

                    b.Property<int>("AntelacionMinimaHoras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("antelacion_minima_horas");

                    b.Property<string>("CalendarProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("google")
                        .HasColumnName("calendar_provider");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre_comercial");

                    b.Property<int>("Recordatorio1Horas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(24)
                        .HasColumnName("recordatorio_1_horas");

                    b.Property<int>("Recordatorio2Horas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("recordatorio_2_horas");

                    b.Property<bool>("RecordatorioHabilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("recordatorio_habilitado");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("WhatsAppPhoneNumberId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("whatsapp_phone_number_id");

                    b.HasKey("IdTenant");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.TurnFailure", b =>
                {
                    b.Property<Guid>("IdTurnFailure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_turn_failure");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("motivo");

                    b.Property<string>("PhoneCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("phone_cliente");

                    b.HasKey("IdTurnFailure");

                    b.HasIndex("FechaCreacion");

                    b.ToTable("turn_failures", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.WaitlistEntry", b =>
                {
                    b.Property<Guid>("IdWaitlistEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_waitlist_entry");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_desde");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hasta");

                    b.Property<Guid>("IdClient")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_client");

                    b.Property<Guid?>("IdProfessional")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_professional");

                    b.Property<Guid>("IdServiceType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_service_type");

                    b.Property<Guid>("IdTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tenant");

                    b.HasKey("IdWaitlistEntry");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdProfessional");

                    b.HasIndex("IdServiceType");

                    b.HasIndex("IdTenant", "Estado");

                    b.HasIndex("IdTenant", "IdServiceType", "IdProfessional", "Estado");

                    b.ToTable("waitlist_entries", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("AgendaApi.Domain.Entities.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaApi.Domain.Entities.Professional", "Professional")
                        .WithMany("Appointments")
                        .HasForeignKey("IdProfessional")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgendaApi.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("IdServiceType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaApi.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Appointments")
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Professional");

                    b.Navigation("ServiceType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.AvailabilityException", b =>
                {
                    b.HasOne("AgendaApi.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.AvailabilityRule", b =>
                {
                    b.HasOne("AgendaApi.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AvailabilityRules")
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.CalendarConnection", b =>
                {
                    b.HasOne("AgendaApi.Domain.Entities.Tenant", "Tenant")
                        .WithOne("CalendarConnection")
                        .HasForeignKey("AgendaApi.Domain.Entities.CalendarConnection", "IdTenant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.Client", b =>
                {
                    b.HasOne("AgendaApi.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Clients")
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.Professional", b =>
                {
                    b.HasOne("AgendaApi.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Professionals")
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.ProfessionalService", b =>
                {
                    b.HasOne("AgendaApi.Domain.Entities.Professional", "Professional")
                        .WithMany("Services")
                        .HasForeignKey("IdProfessional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaApi.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("IdServiceType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professional");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.ReminderLog", b =>
                {
                    b.HasOne("AgendaApi.Domain.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("IdAppointment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.ServiceType", b =>
                {
                    b.HasOne("AgendaApi.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.WaitlistEntry", b =>
                {
                    b.HasOne("AgendaApi.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaApi.Domain.Entities.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("IdProfessional")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgendaApi.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("IdServiceType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaApi.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Professional");

                    b.Navigation("ServiceType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.Client", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.Professional", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("AgendaApi.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AvailabilityRules");

                    b.Navigation("CalendarConnection");

                    b.Navigation("Clients");

                    b.Navigation("Professionals");

                    b.Navigation("ServiceTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
